### PR TITLE
Changes for 2.1 release

### LINKED ISSUE #43: NTFS Support broken (regression)
It seems the latest release fails with NTFS USB keys...

### LINKED ISSUE #48: LED removed
Pull #46 removed the scripts for the LED and removed the entry from rc.local.

### PR DESCRIPTION
**Pull request by dputtick**
- Add changes to changelog from circl website
- Various other documentation fixes
- Fix NTFS support (fixes #43)
- Turn on noswap, turn off display sleep
- Add debug logging functionality and debug flag
- Re-add led files (fixes #48)
- Make timidity terminal output quieter
- Add an image setup checklist

### CODE REVIEW

**Comment by dputtick** [comment]
@Rafiot Probably shouldn't merge this until we confirm the udev rules work on all raspberry pi versions. I'll add a 2.1 release tag after the merge.

**Comment by Rafiot** [comment]
Sounds good, I'll work on it tomorrow, or later today.

Thank you very much!

**Comment by dputtick** [comment]
@Beercow oof good catch. Fixed.

**Comment by Rafiot** [comment]
Looks great, it seems the USB keys are mounted properly, I'm doing a few more tests, but I think we will officially do a release today :)

Thank you very much!

**Pull request merged**
